In [1]:
import pandas as pd

In [2]:
from pycaret.classification import *

In [3]:
df = pd.read_csv("16P.csv", encoding="ISO-8859-1")

In [4]:
df.head()

,Response Id,You regularly make new friends.,You spend a lot of your free time exploring various random topics that pique your interest,Seeing other people cry can easily make you feel like you want to cry too,You often make a backup plan for a backup plan.,"You usually stay calm, even under a lot of pressure","At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know",You prefer to completely finish one project before starting another.,You are very sentimental.,You like to use organizing tools like schedules and lists.,...,You believe that pondering abstract philosophical questions is a waste of time.,"You feel more drawn to places with busy, bustling atmospheres than quiet, intimate places.",You know at first glance how someone is feeling.,You often feel overwhelmed.,You complete things methodically without skipping over any steps.,You are very intrigued by things labeled as controversial.,You would pass along a good opportunity if you thought someone else needed it more.,You struggle with deadlines.,You feel confident that things will work out for you.,Personality
0,0,0,0,0,0,0,1,1,0,0,...,0,0,0,-1,0,0,0,0,0,ENFP
1,1,0,0,-2,-3,-1,2,-2,0,3,...,0,-2,0,2,0,-1,-1,-1,3,ISFP
2,2,0,0,2,0,-1,2,0,0,1,...,0,2,0,2,-1,0,1,2,1,INFJ
3,3,0,-1,3,-1,0,0,-2,0,-2,...,0,0,-1,-1,0,1,0,-2,-1,ISTP
4,4,0,0,-1,0,2,-1,-2,0,1,...,0,1,0,2,0,1,-1,2,-1,ENFJ

In [5]:
setup(df,target="Personality")

In [6]:
df.Personality.nunique()

16

In [7]:
df["Personality"].unique()

array(['ENFP', 'ISFP', 'INFJ', 'ISTP', 'ENFJ', 'INTJ', 'ENTJ', 'ESFP',
       'INFP', 'INTP', 'ISTJ', 'ENTP', 'ISFJ', 'ESTJ', 'ESTP', 'ESFJ'],
      dtype=object)

In [8]:
df["Personality"]=df["Personality"].replace("ENFP",1)
df["Personality"]=df["Personality"].replace("ISFP",2)
df["Personality"]=df["Personality"].replace("INFJ",3)
df["Personality"]=df["Personality"].replace("ISTP",4)
df["Personality"]=df["Personality"].replace("ENFJ",5)
df["Personality"]=df["Personality"].replace("INTJ",6)
df["Personality"]=df["Personality"].replace("ENTJ",7)
df["Personality"]=df["Personality"].replace("ESFP",8)
df["Personality"]=df["Personality"].replace("INFP",9)
df["Personality"]=df["Personality"].replace("INTP",10)
df["Personality"]=df["Personality"].replace("ISTJ",11)
df["Personality"]=df["Personality"].replace("ENTP",12)
df["Personality"]=df["Personality"].replace("ISFJ",13)
df["Personality"]=df["Personality"].replace("ESTJ",14)
df["Personality"]=df["Personality"].replace("ESTP",15)
df["Personality"]=df["Personality"].replace("ESFJ",16)

In [9]:
compare_models()

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [10]:
dt=create_model("dt",fold=10)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [11]:
dt=create_model("dt")

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [12]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
y=df["Personality"]

In [15]:
x=df.drop("Personality", axis=1)

In [16]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20, random_state=42)

In [17]:
q=QuadraticDiscriminantAnalysis()

In [18]:
q.fit(x,y)

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [19]:
x=pd.get_dummies(x,drop_first=True)

In [20]:
from sklearn.metrics import roc_auc_score

In [21]:
tahmin=q.predict(x)

In [22]:
roc_auc_score(tahmin,y)

ValueError: multi_class must be in ('ovo', 'ovr')